### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by BurAndBYsAlt** [TheDarkSid3r/jbg-dummy-players#1]
bundle.js:2 WebSocket connection to 'wss://ecast.jackboxgames.com/api/v2/rooms/KZGC/play?role=player&name=THXSID3R-1&format=json&user-id=9484c016-8b22-48a3-a052-6726a0f932c2&password=' failed:

**Comment by TheDarkSid3r** [comment]
have you tried it again recently?

**Comment by BurAndBY** [comment]
> have you tried it again recently?

For some reason it works today.
P.S.: Is there any way to contact you?

**Comment by TheDarkSid3r** [comment]
by email (sid3rdark@gmail.com) or [on Discord](https://discord.gg/ENuEwUUwfr)
